[package]
name = "moyo"
version = "0.1.0"
authors = ["Kohei Shinohara <kshinohara0508@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Library for Crystal Symmetry in Rust"
repository = "https://github.com/lan496/moyo"

[lib]
name = "moyo"

[dependencies]
nalgebra = "0.32.3"
itertools = "0.11.0"
approx = "0.5.1"
thiserror = "1.0"
union-find = "0.4.2"
strum = "0.25"
strum_macros = "0.25"

[dev-dependencies]
rand = "0.8.5"
rstest = "0.18.2"
