name: moyo CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main]

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --all -- --nocapture
